import type { Metadata } from 'next'
import { Suspense } from 'react'
import { ReduxProvider } from '@/redux/provider'

// [publish]
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import '@styles/fonts/pretendard.css'
import { Flowbite } from 'flowbite-react';
import theme from '@styles/theme'

// [Layout]
import Navbar from '@/layout/Navbar';
import Footer from '@/layout/Footer';

// [Common Components]
import Script from 'next/script'
import Toast from '@/components/Toast/ToastModal'
import AlertDialog from '@/components/Alert/AlertDialog'
import ConfirmDialog from '@/components/Alert/ConfirmDialog'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='text-lato'>
        <Flowbite theme={{ theme }}>
          <ReduxProvider>
            <Navbar />
            {children}
            <Footer />

            <Toast />
            <AlertDialog />
            <ConfirmDialog />

          </ReduxProvider>
        </Flowbite>
        {/* <Script src="https://cdnjs.cloudflare.com/ajax/libs/paper.js/0.12.17/paper-full.min.js" /> */}
      </body>
    </html>
  )
}
