import type { FlowbiteButtonTheme } from '@/components/Button/Button';

const button: FlowbiteButtonTheme = {
  base: 'group flex items-stretch items-center justify-center min-w-20 min-h-10 text-center font-medium relative border focus:outline-none',
  fullSized: 'w-full',
  color: {
    default: 'text-white bg-primary-500 border-transparent enabled:hover:bg-primary-400 enabled:focus:bg-primary-300',
    red: 'text-white bg-red-500 border-transparent enabled:hover:bg-red-900 enabled:focus:bg-red-800',
    dark: 'text-white bg-gray-500 border-transparent enabled:hover:bg-gray-900 enabled:focus:bg-gray-800',
    blue: 'text-white bg-blue-500 border-transparent enabled:hover:bg-blue-900 enabled:focus:bg-blue-800',
    green: 'text-white bg-green-500 border-transparent enabled:hover:bg-green-900 enabled:focus:bg-green-800',
    purple: 'text-white bg-purple-500 border-transparent enabled:hover:bg-purple-900 enabled:focus:bg-purple-800 ',
    gray: 'text-white bg-gray-500 border-transparent enabled:hover:bg-gray-900 enabled:focus:bg-gray-800',
    failure: 'text-white bg-red-500 border-transparent enabled:hover:bg-red-900 enabled:focus:bg-red-800',
    info: 'text-white bg-cyan-500 border-transparent enabled:hover:bg-cyan-900 enabled:focus:bg-cyan-800',
    light: 'text-white border-natural-200 enabled:hover:bg-natural-100 enabled:focus:bg-natural-50',
    success: 'text-white bg-green-500 border-transparent  enabled:hover:bg-green-900 enabled:focus:bg-green-800',
    warning: 'text-white bg-yellow-500 border-transparent  enabled:hover:bg-yellow-900 enabled:focus:bg-yellow-800',
    cyan: 'text-white border-cyan-50  enabled:hover:bg-cyan-900 enabled:focus:bg-cyan-800',
    indigo: 'text-white border-indigo-500  enabled:hover:bg-indigo-900 enabled:focus:bg-indigo-800',
    lime: 'text-white border-lime-500  enabled:hover:bg-lime-900 enabled:focus:bg-lime-800',
    pink: 'text-white border-pink-500  enabled:hover:bg-pink-900 enabled:focus:bg-pink-800',
    teal: 'text-white border-teal-500  enabled:hover:bg-teal-900 enabled:focus:bg-teal-800',
    yellow: 'text-white border-yellow-500  enabled:hover:bg-yellow-900 enabled:focus:bg-yellow-800',
  },
  disabled: 'cursor-not-allowed bg-gray-200',

  label: 'l-2 inline-flex h-4 w-4 items-center justify-center rounded-full bg-cyan-500 text-xs font-semibold text-cyan-500',
  outline: {
    color: {
      default: 'text-primary-500 bg-transparent border border-primary-500 enabled:hover:bg-primary-50 enabled:focus:bg-gray-50',
      red: 'text-red-500 bg-transparent border border-red-500 enabled:hover:bg-red-50 enabled:focus:bg-red-50',
      dark: 'text-gray-500 bg-transparent border border-gray-500 enabled:hover:bg-gray-50 enabled:focus:bg-gray-50',
      blue: 'text-blue-500 bg-transparent border border-blue-500 enabled:hover:bg-blue-50 enabled:focus:bg-blue-50',
      green: 'text-green-500 bg-transparent border border-green-500 enabled:hover:bg-green-50 enabled:focus:bg-green-50',
      purple: 'text-purple-500 bg-transparent border border-purple-500 enabled:hover:bg-purple-50 enabled:focus:bg-purple-50',
      gray: 'text-gray-500 bg-transparent border border-gray-500 enabled:hover:bg-gray-50 enabled:focus:bg-gray-50',
      failure: 'text-red-500 bg-transparent border border-red-500 enabled:hover:bg-red-50 enabled:focus:bg-red-50',
      info: 'text-cyan-500 bg-transparent border border-cyan-500 enabled:hover:bg-cyan-50 enabled:focus:bg-cyan-50',
      light: 'text-natural-500 bg-transparent border border-natural-500 enabled:hover:bg-natural-50 enabled:focus:bg-natural-50',
      success: 'text-green-500 bg-transparent border border-green-500 enabled:hover:bg-green-50 enabled:focus:bg-green-50',
      warning: 'text-yellow-500 bg-transparent border border-yellow-500 enabled:hover:bg-yellow-50 enabled:focus:bg-yellow-50',
      cyan: 'text-cyan-500 bg-transparent border border-cyan-500 enabled:hover:bg-cyan-50 enabled:focus:bg-cyan-50',
      indigo: 'text-indigo-500 bg-transparent border border-indigo-500 enabled:hover:bg-indigo-50 enabled:focus:bg-indigo-50',
      lime: 'text-lime-500 bg-transparent border border-lime-500 enabled:hover:bg-lime-50 enabled:focus:bg-lime-50',
      pink: 'text-pink-500 bg-transparent border border-pink-500 enabled:hover:bg-pink-50 enabled:focus:bg-pink-50',
      teal: 'text-teal-500 bg-transparent border border-teal-500 enabled:hover:bg-teal-50 enabled:focus:bg-teal-50',
      yellow: 'text-yellow-500 bg-transparent border border-yellow-500 enabled:hover:bg-yellow-50 enabled:focus:bg-yellow-50',
    },
    off: '',
    on: 'flex justify-center transition-all duration-75 ease-in group-enabled:group-hover:bg-opacity-0 group-enabled:group-hover:text-inherit  w-full',
    pill: {
      off: '',
      on: 'rounded-full',
    },
  },
  pill: {
    off: 'rounded-md',
    on: 'rounded-full',
  },

  width: {
    '1': 'w-1',
    '1.5': 'w-1.5',
    '2': 'w-2',
    '2.5': 'w-2.5',
    '3': 'w-3',
    '3.5': 'w-3.5',
    '4': 'w-4',
    '5': 'w-5',
    '6': 'w-6',
    '7': 'w-7',
    '8': 'w-8',
    '9': 'w-9',
    '10': 'w-10',
    '11': 'w-11',
    '12': 'w-12',
    '14': 'w-14',
    '16': 'w-16',
    '20': 'w-20',
    '24': 'w-24',
    '28': 'w-28',
    '32': 'w-32',
    '36': 'w-36',
    '40': 'w-40',
    '44': 'w-44',
    '48': 'w-48',
    '52': 'w-52',
    '56': 'w-56',
    '60': 'w-60',
    '64': 'w-64',
    '72': 'w-72',
    '80': 'w-80',
    '96': 'w-96',
    'auto': 'w-auto',
    '1/2': 'w-1/2',
    '1/3': 'w-1/3',
    '2/3': 'w-2/3',
    '1/4': 'w-1/4',
    '2/4': 'w-2/4',
    '3/4': 'w-3/4',
    '1/5': 'w-1/5',
    '2/5': 'w-2/5',
    '3/5': 'w-3/5',
    '4/5': 'w-4/5',
    '1/6': 'w-1/6',
    '2/6': 'w-2/6',
    '3/6': 'w-3/6',
    '4/6': 'w-4/6',
    '5/6': 'w-5/6',
    '1/12': 'w-1/12',
    '2/12': 'w-2/12',
    '3/12': 'w-3/12',
    '4/12': 'w-4/12',
    '5/12': 'w-5/12',
    '6/12': 'w-6/12',
    '7/12': 'w-7/12',
    '8/12': 'w-8/12',
    '9/12': 'w-9/12',
    '10/12': 'w-10/12',
    '11/12': 'w-11/12',
    'full': 'w-full',
  }

};

export default button