import dropdown from './dropdown.theme'
import table from './table.theme'
import checkbox from './checkbox.theme'
import accordion from './accordion.theme'
import textarea from './textarea.theme'
import radio from './radio.theme'
import pagination from './pagination.theme'
import modal from './modal.theme'
import fileInput from './fileInput.theme'
import toast from './toast.theme'
import button from './button.theme'
import textInput from './input.theme'
export default { dropdown, table, checkbox, accordion, textarea, radio, pagination, modal, fileInput, toast, button, textInput }